version: "3"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./API:/var/www
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./API/app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  db:
    image: postgres:15-alpine
    environment:
      - "POSTGRES_DB=jump_park"
      - "POSTGRES_USER=laravel"
      - "POSTGRES_PASSWORD=secreto1"
    networks:
      - laravel
    ports:
      - "5432:5432"
      - "5441:5432"
    volumes:
      - postgres-teste-dev:/var/lib/postgresql/data

networks:
  laravel:


volumes:
  postgres-teste-dev: 
